name: Pull Request Checks

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
      - name: Test API
        run: |
          cd apps/api
          go test ./...
